### ISSUE TITLE
Criar Tabela do Escalonador

### ISSUE THREAD

**Issue by victoragcosta** [AndreLaranjeira/ProgramScheduler#9]
Precisa conter:
* Número do job
* argc
* argv
* tempo quando deve ser executado

> OBS: a execução é marcada com signal alarm e toda vez que um programa chega, ele é adicionado na tabela, cancela o alarm, acha o menor tempo da tabela e coloca o signal alarm para esse. Quando der signal, envia-se o programa para ser executado e é colocado o signal para o próximo.

**Comment by Hugo-NF** [comment]
O scheduler deve receber mensagens do execute e armazena-las. O scheduler deve imprimir os processos que serão executados após o tempo delay.
